server:
  servlet:
    context-path: /ypt
#App相关的key配置
youpintao:
  adZoneId: 66968300266
  siteId: 43360697
  url: http://gw.api.taobao.com/router/rest
  appKey: 25256525
  appSecret: 1f439c0212f0e7d69525edeb82a1ba93


#商品类目相关配置     总合，女装，家居家装，数码家电，母婴，食品，鞋包饰品，美妆个护，男装，内衣，运动户外，天猫国际
category:
  catIds: 50002766,16,50020808,50020485,50008165,50002766,122852001,1801,30,1625,50013886,35
  catNames: 综合,女装,家居家装,数码家电,母婴,食品,鞋包饰品,美妆个护,男装,内衣,运动户外,天猫国际

newuser:
  activityId: 119106_12
  settleMonth: 201812

authCodeUrl: http://my.open.taobao.com/auth/authorize.htm



#喵有券开发平台
myj:
 url: https://api.open.21ds.cn/apiv1/getitemgyurl
 apkey: 14eff147-3b4a-3af5-b1dc-27c043dc980c
 pid: mm_126935412_43360697_66968300266
 tbname: 喏风尘梦