#spring:
#  data:
#    elasticsearch:
#         cluster-nodes: 47.105.99.130:9300
#         cluster-name: test-es
server:
  servlet:
    context-path: /ypt

youpintao:
  adZoneId: 66968300266
  url: http://gw.api.taobao.com/router/rest
  appKey: 25256525
  appSecret: 1f439c0212f0e7d69525edeb82a1ba93


#商品类目相关配置     总合，女装，家居家装，数码家电，母婴，食品，鞋包饰品，美妆个护，男装，内衣，运动户外，天猫国际
category:
   catIds: 50002766,16,50020808,50020485,50008165,50002766,122852001,1801,30,1625,50013886,35
   catNames: 综合,女装,家居家装,数码家电,母婴,食品,鞋包饰品,美妆个护,男装,内衣,运动户外,天猫国际